### ISSUE TITLE
Error when loading pkg

### ISSUE THREAD

**Issue by laynor** [TieDyedDevil/apl-pkg#1]
Platform: Arch Linux x64,  gnu APL version 1.5 / 9529

When I `)LOAD pkg`, I get the following output:

    loading )DUMP file /home/ale/src/apl/workspaces/pkg.apl...

    WAS CLEAR WS
    VALUE ERROR
          'pkg∆shell_version' pkg⍙constant pkg_
                                       ^
         User-defined command ]pkg installed. 
    VALUE ERROR
          pkg⍙process_cmdline pkg⍙get_cmdline

The `]pkg` command does not appear to be defined in the end.

**Comment by TieDyedDevil** [comment]
Am I correct in assuming that version 1.5 / 9529 is the "release" version? If so, would you please build APL from the SVN version? The 1.5 release is quite old; there have been many changes.

**Comment by laynor** [comment]
I just built it from the svn repo, now the apl repl displays  version 1.5 / 725

                     Welcome to GNU APL version 1.5 / 725

Seems odd. I get the same error message, fwiw.

**Comment by TieDyedDevil** [comment]
So you're saying that the instance installed using zsh doesn't work, while the instance installed using bash does?

Perhaps there's some bash-ism in the install script that's silently tripping up zsh. OTOH, why wouldn't your system honor the #! on the first line of install.sh?

**Comment by laynor** [comment]
My system appears to honor the shebang, but the code in probe.apl checks the `SHELL` environment variable, which is set to `/bin/zsh`.

**Comment by TieDyedDevil** [comment]
OK, I see. Thank you for isolating that.

I'll fix this in the `percy` branch. Meanwhile, here's a patch that you can use:

``` diff
diff --git a/src/probe.apl b/src/probe.apl
index 1dd3795..300ff1b 100644
--- a/src/probe.apl
+++ b/src/probe.apl
@@ -127,6 +127,7 @@ pkg⍙⍙run_probe 'os_distribution' 'debian'
 
 ⍎pkg⍙⍙probe_bash_shell_type/'pkg_←pkg⍙sh_cmd_version ''bash --version'''
 ⍎pkg⍙⍙probe_yash_shell_type/'pkg_←pkg⍙sh_cmd_version ''yash --version'''
+⍎(0=⎕nc 'pkg_')/'pkg_←''unknown'''
 'pkg∆shell_version' pkg⍙constant pkg_
 0 0⍴⎕ex 'pkg_'
 
```
